variable "sever_count" {}
variable "compartment_ocid" {}
variable "availability_domain" {}
variable "image_ocid" {}
variable "display_name_prefix" {}
variable "assign_public_ipaddress" {}
variable "subnet_ocid" {}
variable "network_security_group_id" {}
variable "ssh_private_key" {}
variable "ssh_public_key" {}
variable "instance_shape" {}
variable "instance_memory_in_gbs" {}
variable "instance_nb_of_ocpus" {}
variable "is_testing_required" {}
variable "is_website_installed" {}
variable "is_loadbalancer_installed" {}
variable "lb_min_bandwith_in_mgps" {}
variable "lb_max_bandwith_in_mgps" {}
